# Generated by Django 5.1.1 on 2024-09-13 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=255)),
                ('prononciation_audio', models.FileField(blank=True, null=True, upload_to='pronunciations/')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionnaire.langue')),
            ],
        ),
        migrations.CreateModel(
            name='Traduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemple', models.TextField(blank=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mot_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traductions_cible', to='dictionnaire.mot')),
                ('mot_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traductions_source', to='dictionnaire.mot')),
            ],
            options={
                'unique_together': {('mot_source', 'mot_cible')},
            },
        ),
    ]
