# Generated by Django 5.1.1 on 2024-09-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mot',
            name='image_illustrative',
            field=models.ImageField(blank=True, null=True, upload_to='mot_images/'),
        ),
    ]
