# Generated by Django 5.1.1 on 2024-09-18 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la culture')),
                ('language', models.CharField(max_length=100, verbose_name='Langue principale')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('description', models.TextField(verbose_name='Description générale')),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional_dishes', models.TextField(verbose_name='Plats traditionnels')),
                ('local_ingredients', models.TextField(verbose_name='Ingrédients locaux')),
                ('cooking_techniques', models.TextField(verbose_name='Techniques de préparation')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingAndAdornments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional_outfits', models.TextField(verbose_name='Tenues traditionnelles')),
                ('jewelry_and_accessories', models.TextField(verbose_name='Bijoux et accessoires')),
                ('patterns_and_colors', models.TextField(verbose_name='Signification des motifs et couleurs')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='ArtAndCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_and_instruments', models.TextField(verbose_name='Musique et instruments traditionnels')),
                ('dances', models.TextField(verbose_name='Danses')),
                ('visual_arts', models.TextField(verbose_name='Sculpture et peinture')),
                ('textile_arts', models.TextField(verbose_name='Tissage et création de vêtements')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='art', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='AgricultureAndEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agricultural_techniques', models.TextField(verbose_name='Techniques agricoles')),
                ('livestock', models.TextField(verbose_name='Élevage')),
                ('crafts_and_trade', models.TextField(verbose_name='Artisanat et commerce')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economy', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_management', models.TextField(verbose_name='Gestion des ressources naturelles')),
                ('ecological_knowledge', models.TextField(verbose_name='Connaissances écologiques traditionnelles')),
                ('sacred_sites', models.TextField(verbose_name='Sites sacrés')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='GamesAndEntertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childrens_games', models.TextField(verbose_name="Jeux d'enfants")),
                ('traditional_sports', models.TextField(verbose_name='Sports traditionnels')),
                ('recreational_activities', models.TextField(verbose_name='Activités récréatives')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entertainment', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAndOrigins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_myths', models.TextField(verbose_name='Mythes fondateurs')),
                ('historical_migrations', models.TextField(verbose_name='Migrations historiques')),
                ('important_figures', models.TextField(verbose_name='Personnages importants')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialects', models.TextField(verbose_name='Dialectes et variations')),
                ('idiomatic_expressions', models.TextField(verbose_name='Expressions idiomatiques')),
                ('non_verbal_communication', models.TextField(verbose_name='Système de communication non-verbale')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_details', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='OralLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tales_and_legends', models.TextField(verbose_name='Contes et légendes')),
                ('proverbs', models.TextField(verbose_name='Proverbes et dictons')),
                ('traditional_songs', models.TextField(verbose_name='Chants traditionnels')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='literature', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='ReligionAndBeliefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deities_and_spirits', models.TextField(verbose_name='Divinités et esprits')),
                ('religious_practices', models.TextField(verbose_name='Pratiques religieuses')),
                ('superstitions', models.TextField(verbose_name='Superstitions')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='religion', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='SocialStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_organization', models.TextField(verbose_name='Organisation familiale')),
                ('social_hierarchy', models.TextField(verbose_name='Hiérarchie sociale')),
                ('gender_roles', models.TextField(verbose_name='Rôles de genre')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_structure', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionalGovernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chieftaincy', models.TextField(verbose_name='Chefferies')),
                ('council_of_elders', models.TextField(verbose_name='Conseils des anciens')),
                ('conflict_resolution', models.TextField(verbose_name='Mécanismes de résolution des conflits')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionalHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_architecture', models.TextField(verbose_name='Architecture des maisons')),
                ('community_organization', models.TextField(verbose_name='Organisation du village ou de la communauté')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitat', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionalMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinal_plants', models.TextField(verbose_name='Plantes médicinales')),
                ('healing_practices', models.TextField(verbose_name='Pratiques de guérison')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='culture.culture')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionsAndCustoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rites_of_passage', models.TextField(verbose_name='Rites de passage')),
                ('traditional_ceremonies', models.TextField(verbose_name='Cérémonies traditionnelles')),
                ('festivals', models.TextField(verbose_name='Fêtes et célébrations')),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traditions', to='culture.culture')),
            ],
        ),
    ]
