# Generated by Django 5.1.1 on 2024-09-19 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
        ('dictionnaire', '0002_mot_image_illustrative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artandcraft',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='clothingandadornments',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='language',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='religionandbeliefs',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='environmentalrelationship',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='traditionalgovernance',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='traditionalhabitat',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='historyandorigins',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='socialstructure',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='gamesandentertainment',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='traditionsandcustoms',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='oralliterature',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='traditionalmedicine',
            name='culture',
        ),
        migrations.CreateModel(
            name='ElementCulturel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('CHANT', 'Chant'), ('CONTE', 'Conte'), ('LEGENDE', 'Légende'), ('HISTOIRE', 'Histoire'), ('COUTUME', 'Coutume et Tradition'), ('SOCIAL', 'Structure Sociale'), ('ART', 'Art'), ('DANSE', 'Danse'), ('GOUVERNANCE', 'Gouvernance Traditionnelle'), ('RELIGION', 'Religion'), ('MEDECINE', 'Médecine Traditionnelle'), ('JEU', 'Jeux et Divertissements'), ('AUTRE', 'Autre')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_culturels', to='dictionnaire.langue')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('element_culturel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='culture.elementculturel')),
            ],
        ),
        migrations.CreateModel(
            name='MediaCulturel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document')], max_length=10)),
                ('fichier', models.FileField(upload_to='culture_medias/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('element_culturel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='culture.elementculturel')),
            ],
        ),
        migrations.DeleteModel(
            name='AgricultureAndEconomy',
        ),
        migrations.DeleteModel(
            name='ArtAndCraft',
        ),
        migrations.DeleteModel(
            name='ClothingAndAdornments',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='ReligionAndBeliefs',
        ),
        migrations.DeleteModel(
            name='EnvironmentalRelationship',
        ),
        migrations.DeleteModel(
            name='TraditionalGovernance',
        ),
        migrations.DeleteModel(
            name='TraditionalHabitat',
        ),
        migrations.DeleteModel(
            name='HistoryAndOrigins',
        ),
        migrations.DeleteModel(
            name='SocialStructure',
        ),
        migrations.DeleteModel(
            name='GamesAndEntertainment',
        ),
        migrations.DeleteModel(
            name='TraditionsAndCustoms',
        ),
        migrations.DeleteModel(
            name='OralLiterature',
        ),
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.DeleteModel(
            name='TraditionalMedicine',
        ),
    ]
